<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <title>Blog</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/fonts/icomoon/style.css">   
    <link rel="stylesheet" href="/fonts/Stroke-Gap-Icons-Webfont/style.css">       
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https:/stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/details.css">
  	<script src="/js/jquery-3.4.0.js"></script>
    <style rel="stylesheet"> 
    	.user-menu{
    		display:none;
    		position:absolute;
    		top:30px;
    		right:60px;
    		flex-direction:column;
    		background-color:#f6f6f6;
    		padding:10px;
    		border-radius:5px;
    	}
    	.user-menu a{
    		border-bottom: 1px solid silver;
    	}
    	.user-menu a:hover{
    		color:#ff7f00;
    	}
    	div.account{
    		position:relative;
    	}
    	.active{
    		background-color: #ff7f00;
    		color:#fff !important;
    	}
    	a{
    		padding: 3px;
    		color:inherit;
    		text-decoration: none !important;
    	}
    	a:hover{
    		color:inherit;
    	}
    </style>
</head>
<body>
<div class="page">
    @include('include.header')
    @include('include.massege')
    <div class="section flex flex-justify-center">
        @yield('content')
    </div>
</div>
    @include('include.footer')

<script src="/js/js.js"></script>
</body>
</html>